# Dockerfile modèle pour déployer PocketBase sur CapRover en mettant à jour le TAG de l'image

FROM alpine:3.19.1
RUN apk add --no-cache unzip openssh
ADD https://github.com/pocketbase/pocketbase/releases/download/v0.22.11/pocketbase_0.22.11_linux_amd64.zip /tmp/pb.zip
RUN unzip /tmp/pb.zip -d /pb/
EXPOSE 8080
CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:8080"]